import type { INodeProperties } from 'n8n-workflow';

const show = (operations: string[]) => ({
	displayOptions: { show: { resource: ['pipeline'], operation: operations } },
});
const selected = ['get', 'update', 'delete', 'enable', 'disable'];

export const pipelineProperties: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'create',
		displayOptions: { show: { resource: ['pipeline'] } },
		options: [
			{ name: 'Create', value: 'create', action: 'Create a pipeline' },
			{ name: 'Delete', value: 'delete', action: 'Delete a pipeline' },
			{ name: 'Disable', value: 'disable', action: 'Disable a pipeline' },
			{ name: 'Enable', value: 'enable', action: 'Enable a pipeline' },
			{ name: 'Get', value: 'get', action: 'Get a pipeline' },
			{ name: 'Get History', value: 'getHistory', action: 'Get pipeline history' },
			{ name: 'Get Many', value: 'getMany', action: 'Get many pipelines' },
			{ name: 'Update', value: 'update', action: 'Update a pipeline' },
		],
	},
	{
		displayName: 'Pipeline',
		name: 'pipelineId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		...show(selected),
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchPipelines', searchable: true },
			},
			{ displayName: 'By ID', name: 'id', type: 'string' },
		],
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		...show(['create']),
	},
	{
		displayName: 'Description',
		name: 'description',
		type: 'string',
		default: '',
		...show(['create']),
	},
	{
		displayName: 'Type',
		name: 'pipelineType',
		type: 'options',
		default: 'realtime',
		...show(['create']),
		options: [
			{ name: 'Real-Time', value: 'realtime' },
			{ name: 'Scheduled', value: 'scheduled' },
		],
	},
	{ displayName: 'Enabled', name: 'enabled', type: 'boolean', default: true, ...show(['create']) },
	{
		displayName: 'Pipeline JSON',
		name: 'pipelineJson',
		type: 'json',
		required: true,
		default: '',
		description:
			'Required complete source and graph object with non-empty nodes and valid edges. Include a real-time stream input or scheduled query input and at least one output. Real-time graphs must retain a route back to the source stream if unmatched events must be stored.',
		...show(['create']),
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		default: {},
		placeholder: 'Add Field',
		description:
			'Friendly fields to replace; omitted fields retain their current values and Advanced Update JSON is applied first',
		...show(['update']),
		options: [
			{
				displayName: 'Advanced Update JSON',
				name: 'pipelineJson',
				type: 'json',
				default: '{}',
				description:
					'Supplements Update Fields by merging other supported fields into the complete current definition; friendly fields win on conflicts and omitted graph fields are preserved',
			},
			{ displayName: 'Description', name: 'description', type: 'string', default: '' },
			{ displayName: 'Enabled', name: 'enabled', type: 'boolean', default: true },
			{ displayName: 'Name', name: 'name', type: 'string', default: '' },
		],
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		...show(['getMany', 'getHistory']),
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		typeOptions: { minValue: 1, maxValue: 1000 },
		description: 'Max number of results to return',
		displayOptions: {
			show: { resource: ['pipeline'], operation: ['getMany', 'getHistory'], returnAll: [false] },
		},
	},
	{
		displayName: 'Pipeline',
		name: 'historyPipelineId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		...show(['getHistory']),
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchPipelines', searchable: true },
			},
			{ displayName: 'By ID', name: 'id', type: 'string' },
		],
	},
	{
		displayName: 'Start Time',
		name: 'startTime',
		type: 'dateTime',
		default: '',
		...show(['getHistory']),
	},
	{
		displayName: 'End Time',
		name: 'endTime',
		type: 'dateTime',
		default: '',
		...show(['getHistory']),
	},
	{
		displayName: 'Sort By',
		name: 'sortBy',
		type: 'options',
		default: 'timestamp',
		options: [
			{ name: 'Delay in Seconds', value: 'delay_in_secs' },
			{ name: 'Duration', value: 'duration' },
			{ name: 'End Time', value: 'end_time' },
			{ name: 'Evaluation Took in Seconds', value: 'evaluation_took_in_secs' },
			{ name: 'Is Partial', value: 'is_partial' },
			{ name: 'Is Real-Time', value: 'is_realtime' },
			{ name: 'Is Silenced', value: 'is_silenced' },
			{ name: 'Pipeline Name', value: 'pipeline_name' },
			{ name: 'Query Took', value: 'query_took' },
			{ name: 'Retries', value: 'retries' },
			{ name: 'Source Node', value: 'source_node' },
			{ name: 'Start Time', value: 'start_time' },
			{ name: 'Status', value: 'status' },
			{ name: 'Timestamp', value: 'timestamp' },
		],
		...show(['getHistory']),
	},
	{
		displayName: 'Sort Order',
		name: 'sortOrder',
		type: 'options',
		default: 'desc',
		options: [
			{ name: 'Ascending', value: 'asc' },
			{ name: 'Descending', value: 'desc' },
		],
		...show(['getHistory']),
	},
	{
		displayName: 'I Understand This Permanently Deletes the Pipeline',
		name: 'confirmDestructive',
		type: 'boolean',
		default: false,
		...show(['delete']),
	},
];
