import type { INodeProperties } from 'n8n-workflow';
const show = (operations: string[]) => ({
	displayOptions: { show: { resource: ['metric'], operation: operations } },
});
const queryOps = ['instantQuery', 'rangeQuery'];
const selectorOps = ['getLabels', 'getLabelValues', 'findSeries'];
export const metricProperties: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['metric'] } },
		default: 'instantQuery',
		options: [
			{ name: 'Find Series', value: 'findSeries', action: 'Find metric series' },
			{ name: 'Get Label Values', value: 'getLabelValues', action: 'Get label values' },
			{ name: 'Get Labels', value: 'getLabels', action: 'Get labels' },
			{ name: 'Get Metadata', value: 'getMetadata', action: 'Get metric metadata' },
			{ name: 'Instant Query', value: 'instantQuery', action: 'Run an instant prom ql query' },
			{ name: 'Range Query', value: 'rangeQuery', action: 'Run a range prom ql query' },
		],
	},
	{
		displayName: 'PromQL',
		name: 'promql',
		type: 'string',
		required: true,
		default: '',
		...show(queryOps),
	},
	{
		displayName: 'Time',
		name: 'queryTime',
		type: 'dateTime',
		default: '',
		...show(['instantQuery']),
	},
	{
		displayName: 'Start',
		name: 'startTime',
		type: 'dateTime',
		default: '',
		required: true,
		...show(['rangeQuery', ...selectorOps]),
	},
	{
		displayName: 'End',
		name: 'endTime',
		type: 'dateTime',
		default: '',
		required: true,
		...show(['rangeQuery', ...selectorOps]),
	},
	{
		displayName: 'Step',
		name: 'step',
		type: 'string',
		default: '60s',
		description: 'Prometheus duration or positive number of seconds',
		...show(['rangeQuery']),
	},
	{
		displayName: 'Series Selectors',
		name: 'selectors',
		type: 'string',
		required: true,
		default: '',
		description: 'One Prometheus selector per line; each is sent as match[]',
		...show(selectorOps),
	},
	{
		displayName: 'Label Name',
		name: 'labelName',
		type: 'string',
		required: true,
		default: '',
		...show(['getLabelValues']),
	},
	{
		displayName: 'Metric Name',
		name: 'metricName',
		type: 'string',
		default: '',
		...show(['getMetadata']),
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		...show(['getMetadata']),
	},
	{
		displayName: 'Timeout',
		name: 'queryTimeout',
		type: 'string',
		default: '',
		description: 'Prometheus duration',
		...show(queryOps),
	},
	{
		displayName: 'Output',
		name: 'rawResponse',
		type: 'options',
		default: false,
		options: [
			{ name: 'Data', value: false },
			{ name: 'Raw Response', value: true },
		],
		...show([...queryOps, 'getMetadata', ...selectorOps]),
	},
];
