import type { INodeProperties } from 'n8n-workflow';

const show = (operations: string[]) => ({
	displayOptions: { show: { resource: ['search'], operation: operations } },
});

export const searchProperties: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['search'] } },
		default: 'query',
		options: [
			{ name: 'Get Field Values', value: 'getFieldValues', action: 'Get field values' },
			{ name: 'Query', value: 'query', action: 'Run a SQL query' },
			{ name: 'Search Around', value: 'searchAround', action: 'Search around a record' },
		],
	},
	{
		displayName: 'Stream Type',
		name: 'streamType',
		type: 'options',
		default: 'logs',
		options: [
			{ name: 'Logs', value: 'logs' },
			{ name: 'Metrics', value: 'metrics' },
			{ name: 'Traces', value: 'traces' },
		],
		...show(['query', 'getFieldValues']),
	},
	{
		displayName: 'Stream Name',
		name: 'streamName',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		...show(['getFieldValues', 'searchAround']),
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchStreams', searchable: true },
			},
			{ displayName: 'By Name', name: 'id', type: 'string' },
		],
	},
	{
		displayName: 'SQL',
		name: 'sql',
		type: 'string',
		typeOptions: { rows: 4 },
		required: true,
		default: '',
		...show(['query']),
	},
	{
		displayName: 'Fields',
		name: 'fields',
		type: 'string',
		required: true,
		default: '',
		description: 'Comma-separated field names',
		...show(['getFieldValues']),
	},
	{
		displayName: 'Around Record JSON',
		name: 'aroundRecordJson',
		type: 'json',
		required: true,
		default: '{}',
		...show(['searchAround']),
	},
	{
		displayName: 'Start',
		name: 'startTime',
		type: 'dateTime',
		required: true,
		default: '',
		...show(['query', 'getFieldValues']),
	},
	{
		displayName: 'End',
		name: 'endTime',
		type: 'dateTime',
		required: true,
		default: '',
		...show(['query', 'getFieldValues']),
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		typeOptions: { minValue: 0 },
		default: 0,
		...show(['query', 'getFieldValues']),
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		displayOptions: { show: { resource: ['search'], operation: ['query'], outputMode: ['rows'] } },
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		displayOptions: {
			show: {
				resource: ['search'],
				operation: ['query'],
				outputMode: ['rows'],
				returnAll: [false],
			},
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		displayOptions: {
			show: { resource: ['search'], operation: ['query'], outputMode: ['raw', 'csv', 'md_table'] },
		},
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		displayOptions: {
			show: { resource: ['search'], operation: ['getFieldValues', 'searchAround'] },
		},
	},
	{
		displayName: 'Filter',
		name: 'filter',
		type: 'string',
		default: '',
		...show(['getFieldValues']),
	},
	{
		displayName: 'Keyword',
		name: 'keyword',
		type: 'string',
		default: '',
		...show(['getFieldValues']),
	},
	{
		displayName: 'Search Type',
		name: 'searchType',
		type: 'options',
		default: '',
		options: [
			{ name: 'Alerts', value: 'alerts' },
			{ name: 'Dashboards', value: 'dashboards' },
			{ name: 'Default', value: '' },
			{ name: 'Reports', value: 'reports' },
			{ name: 'UI', value: 'ui' },
		],
		...show(['query']),
	},
	{
		displayName: 'Timeout (Seconds)',
		name: 'timeout',
		type: 'number',
		typeOptions: { minValue: 0 },
		default: 0,
		...show(['query', 'getFieldValues', 'searchAround']),
	},
	{
		displayName: 'Output',
		name: 'outputMode',
		type: 'options',
		default: 'rows',
		options: [
			{ name: 'CSV', value: 'csv' },
			{ name: 'Markdown Table', value: 'md_table' },
			{ name: 'Raw JSON Response', value: 'raw' },
			{ name: 'Rows', value: 'rows' },
		],
		...show(['query']),
	},
];
