import type { INodeProperties } from 'n8n-workflow';
const show = (operations: string[]) => ({ show: { resource: ['trace'], operation: operations } });
export const traceProperties: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['trace'] } },
		default: 'getLatest',
		options: [
			{ name: 'Get DAG', value: 'getDag', action: 'Get a trace DAG' },
			{ name: 'Get Latest', value: 'getLatest', action: 'Get latest traces' },
		],
	},
	{
		displayName: 'Trace Stream',
		name: 'streamName',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchStreams', searchable: true },
			},
			{ displayName: 'By Name', name: 'id', type: 'string' },
		],
		...show(['getLatest', 'getDag']),
	},
	{
		displayName: 'Trace ID',
		name: 'traceId',
		type: 'string',
		required: true,
		default: '',
		...show(['getDag']),
	},
	{
		displayName: 'Start',
		name: 'startTime',
		type: 'dateTime',
		required: true,
		default: '',
		...show(['getLatest', 'getDag']),
	},
	{
		displayName: 'End',
		name: 'endTime',
		type: 'dateTime',
		required: true,
		default: '',
		...show(['getLatest', 'getDag']),
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number',
		typeOptions: { minValue: 0 },
		default: 0,
		...show(['getLatest']),
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		...show(['getLatest']),
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		displayOptions: { show: { resource: ['trace'], operation: ['getLatest'], returnAll: [false] } },
	},
	{ displayName: 'Filter', name: 'filter', type: 'string', default: '', ...show(['getLatest']) },
	{
		displayName: 'Sort By',
		name: 'sortBy',
		type: 'options',
		default: 'start_time',
		options: [
			{ name: 'Start Time', value: 'start_time' },
			{ name: 'Duration', value: 'duration' },
		],
		...show(['getLatest']),
	},
	{
		displayName: 'Sort Order',
		name: 'sortOrder',
		type: 'options',
		default: 'desc',
		options: [
			{ name: 'Descending', value: 'desc' },
			{ name: 'Ascending', value: 'asc' },
		],
		...show(['getLatest']),
	},
	{
		displayName: 'Timeout (Seconds)',
		name: 'timeout',
		type: 'number',
		typeOptions: { minValue: 0 },
		default: 0,
		...show(['getLatest', 'getDag']),
	},
];
