import type { INodeProperties } from 'n8n-workflow';
const show = (operations: string[]) => ({ show: { resource: ['alert'], operation: operations } });
const selected = ['get', 'update', 'delete', 'enable', 'disable', 'trigger', 'clone', 'export'];
export const alertProperties: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['alert'] } },
		default: 'create',
		options: [
			{ name: 'Clone', value: 'clone', action: 'Clone an alert' },
			{ name: 'Create', value: 'create', action: 'Create an alert' },
			{ name: 'Delete', value: 'delete', action: 'Delete an alert' },
			{ name: 'Disable', value: 'disable', action: 'Disable an alert' },
			{ name: 'Enable', value: 'enable', action: 'Enable an alert' },
			{ name: 'Export', value: 'export', action: 'Export an alert as JSON' },
			{ name: 'Get', value: 'get', action: 'Get an alert' },
			{ name: 'Get History', value: 'getHistory', action: 'Get alert history' },
			{ name: 'Get Many', value: 'getMany', action: 'Get many alerts' },
			{ name: 'Trigger Manually', value: 'trigger', action: 'Trigger an alert manually' },
			{ name: 'Update', value: 'update', action: 'Update an alert' },
		],
	},
	{
		displayName: 'Folder',
		name: 'alertFolder',
		type: 'resourceLocator',
		default: { mode: 'list', value: 'default' },
		required: true,
		...show(['create', ...selected]),
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchAlertFolders', searchable: true },
			},
			{ displayName: 'By ID', name: 'id', type: 'string' },
		],
	},
	{
		displayName: 'Alert',
		name: 'alertId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		...show(selected),
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchAlerts', searchable: true },
			},
			{ displayName: 'By ID', name: 'id', type: 'string' },
		],
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		...show(['create']),
	},
	{
		displayName: 'Stream Type',
		name: 'streamType',
		type: 'options',
		default: 'logs',
		options: [
			{ name: 'Logs', value: 'logs' },
			{ name: 'Metrics', value: 'metrics' },
			{ name: 'Traces', value: 'traces' },
		],
		...show(['create']),
	},
	{
		displayName: 'Stream',
		name: 'streamName',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		...show(['create']),
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchStreams', searchable: true },
			},
			{ displayName: 'By Name', name: 'id', type: 'string' },
		],
	},
	{
		displayName: 'Alert Type',
		name: 'alertType',
		type: 'options',
		default: 'scheduled',
		options: [
			{ name: 'Scheduled', value: 'scheduled' },
			{ name: 'Real-Time', value: 'realtime' },
		],
		...show(['create']),
	},
	{
		displayName: 'Query JSON',
		name: 'queryJson',
		type: 'json',
		required: true,
		default: '{"type":"custom","conditions":null}',
		description:
			'Verified OpenObserve query_condition object. Use type sql with sql, or type promql with promql and promql_condition.',
		...show(['create']),
	},
	{ displayName: 'Threshold', name: 'threshold', type: 'number', default: 1, ...show(['create']) },
	{
		displayName: 'Operator',
		name: 'operator',
		type: 'options',
		default: '>=',
		options: ['=', '!=', '>', '>=', '<', '<='].map((value) => ({ name: value, value })),
		...show(['create']),
	},
	{
		displayName: 'Check Every (Minutes)',
		name: 'frequency',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 10,
		...show(['create']),
	},
	{
		displayName: 'Look Back (Minutes)',
		name: 'period',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 10,
		...show(['create']),
	},
	{
		displayName: 'Cooldown (Minutes)',
		name: 'silence',
		type: 'number',
		typeOptions: { minValue: 0 },
		default: 10,
		...show(['create']),
	},
	{
		// OpenObserve destination references are names, despite the generic dynamic-multi-options lint wording.
		// eslint-disable-next-line n8n-nodes-base/node-param-display-name-wrong-for-dynamic-multi-options
		displayName: 'Destinations',
		name: 'destinations',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAlertDestinations' },
		default: [],
		// eslint-disable-next-line n8n-nodes-base/node-param-description-wrong-for-dynamic-multi-options
		description:
			'Choose destination names from the list, or specify names using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		...show(['create']),
	},
	{
		displayName: 'Description',
		name: 'description',
		type: 'string',
		default: '',
		...show(['create']),
	},
	{ displayName: 'Enabled', name: 'enabled', type: 'boolean', default: false, ...show(['create']) },
	{
		displayName: 'Alert JSON',
		name: 'alertJson',
		type: 'json',
		default: '{}',
		description:
			'Additional supported alert fields; friendly fields take precedence. Anomaly and composite configurations are not supported.',
		...show(['create']),
	},
	{
		displayName: 'Update JSON',
		name: 'alertJson',
		type: 'json',
		default: '{}',
		description:
			'Fields to merge into the complete current alert before replacement; ID and organization fields are preserved',
		...show(['update']),
	},
	{ displayName: 'Clone Name', name: 'cloneName', type: 'string', default: '', ...show(['clone']) },
	{
		displayName: 'Clone Folder',
		name: 'cloneFolder',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		...show(['clone']),
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchAlertFolders', searchable: true },
			},
			{ displayName: 'By ID', name: 'id', type: 'string' },
		],
	},
	{
		displayName: 'Alert ID Filter',
		name: 'historyAlertId',
		type: 'string',
		default: '',
		...show(['getHistory']),
	},
	{
		displayName: 'Start Time',
		name: 'startTime',
		type: 'dateTime',
		default: '',
		...show(['getHistory']),
	},
	{
		displayName: 'End Time',
		name: 'endTime',
		type: 'dateTime',
		default: '',
		...show(['getHistory']),
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		...show(['getMany', 'getHistory']),
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		displayOptions: {
			show: { resource: ['alert'], operation: ['getMany', 'getHistory'], returnAll: [false] },
		},
	},
	{
		displayName: 'I Understand This Permanently Deletes the Alert',
		name: 'confirmDestructive',
		type: 'boolean',
		default: false,
		...show(['delete']),
	},
	{
		displayName: 'I Understand This Sends Notifications',
		name: 'confirmTrigger',
		type: 'boolean',
		default: false,
		...show(['trigger']),
	},
];
