import type { INodeProperties } from 'n8n-workflow';
const show = (operations: string[]) => ({
	displayOptions: { show: { resource: ['alert'], operation: operations } },
});
const selected = ['get', 'update', 'delete', 'enable', 'disable', 'trigger', 'clone', 'export'];
export const alertProperties: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['alert'] } },
		default: 'create',
		options: [
			{ name: 'Clone', value: 'clone', action: 'Clone an alert' },
			{ name: 'Create', value: 'create', action: 'Create an alert' },
			{ name: 'Delete', value: 'delete', action: 'Delete an alert' },
			{ name: 'Disable', value: 'disable', action: 'Disable an alert' },
			{ name: 'Enable', value: 'enable', action: 'Enable an alert' },
			{ name: 'Export', value: 'export', action: 'Export an alert as JSON' },
			{ name: 'Get', value: 'get', action: 'Get an alert' },
			{ name: 'Get History', value: 'getHistory', action: 'Get alert history' },
			{ name: 'Get Many', value: 'getMany', action: 'Get many alerts' },
			{ name: 'Trigger Manually', value: 'trigger', action: 'Trigger an alert manually' },
			{ name: 'Update', value: 'update', action: 'Update an alert' },
		],
	},
	{
		displayName: 'Folder',
		name: 'alertFolder',
		type: 'resourceLocator',
		default: { mode: 'list', value: 'default' },
		required: true,
		...show(['create', 'getMany', ...selected]),
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchAlertFolders', searchable: true },
			},
			{ displayName: 'By ID', name: 'id', type: 'string' },
		],
	},
	{
		displayName: 'Alert',
		name: 'alertId',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		...show(selected),
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchAlerts', searchable: true },
			},
			{ displayName: 'By ID', name: 'id', type: 'string' },
		],
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		...show(['create']),
	},
	{
		displayName: 'Stream Type',
		name: 'streamType',
		type: 'options',
		default: 'logs',
		options: [
			{ name: 'Logs', value: 'logs' },
			{ name: 'Metrics', value: 'metrics' },
			{ name: 'Traces', value: 'traces' },
		],
		...show(['create']),
	},
	{
		displayName: 'Stream',
		name: 'streamName',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		...show(['create']),
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchStreams', searchable: true },
			},
			{ displayName: 'By Name', name: 'id', type: 'string' },
		],
	},
	{
		displayName: 'Alert Type',
		name: 'alertType',
		type: 'options',
		default: 'scheduled',
		options: [
			{ name: 'Scheduled', value: 'scheduled' },
			{ name: 'Real-Time', value: 'realtime' },
		],
		...show(['create']),
	},
	{
		displayName: 'Query JSON',
		name: 'queryJson',
		type: 'json',
		required: true,
		default: '{"type":"custom","conditions":null}',
		description:
			'OpenObserve query condition. The default custom condition matches the stream without a field filter; use conditions to filter, or use type sql with sql or type promql with promql and promql_condition.',
		...show(['create']),
	},
	{ displayName: 'Threshold', name: 'threshold', type: 'number', default: 1, ...show(['create']) },
	{
		displayName: 'Operator',
		name: 'operator',
		type: 'options',
		default: '>=',
		options: ['=', '!=', '>', '>=', '<', '<='].map((value) => ({ name: value, value })),
		...show(['create']),
	},
	{
		displayName: 'Check Every (Minutes)',
		name: 'frequency',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 10,
		displayOptions: {
			show: { resource: ['alert'], operation: ['create'], alertType: ['scheduled'] },
		},
	},
	{
		displayName: 'Look Back (Minutes)',
		name: 'period',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 10,
		displayOptions: {
			show: { resource: ['alert'], operation: ['create'], alertType: ['scheduled'] },
		},
	},
	{
		displayName: 'Cooldown (Minutes)',
		name: 'silence',
		type: 'number',
		typeOptions: { minValue: 0 },
		default: 10,
		...show(['create']),
	},
	{
		displayName: 'Destination Names or IDs',
		name: 'destinations',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getAlertDestinations' },
		required: true,
		default: [],
		description:
			'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		...show(['create']),
	},
	{
		displayName: 'Description',
		name: 'description',
		type: 'string',
		default: '',
		...show(['create']),
	},
	{ displayName: 'Enabled', name: 'enabled', type: 'boolean', default: false, ...show(['create']) },
	{
		displayName: 'Advanced Alert JSON',
		name: 'alertJson',
		type: 'json',
		default: '{}',
		description:
			'Supplements the friendly alert fields with other supported fields; friendly fields win on conflicts. Anomaly and composite configurations are not supported.',
		...show(['create']),
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		description:
			'Friendly fields to replace; omitted fields retain their current values and Advanced Update JSON is applied first',
		...show(['update']),
		options: [
			{
				displayName: 'Advanced Update JSON',
				name: 'alertJson',
				type: 'json',
				default: '{}',
				description:
					'Supplements Update Fields with other supported fields before replacement; nested query and trigger conditions are merged, friendly fields win on conflicts, and identity fields are preserved',
			},
			{
				displayName: 'Check Every (Minutes)',
				name: 'frequency',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 10,
				description: 'Scheduled alerts only',
			},
			{ displayName: 'Cooldown (Minutes)', name: 'silence', type: 'number', default: 10 },
			{
				displayName: 'Description',
				name: 'description',
				type: 'string',
				default: '',
				description: 'May be left empty to clear the current description',
			},
			{
				displayName: 'Destination Names or IDs',
				name: 'destinations',
				type: 'multiOptions',
				typeOptions: { loadOptionsMethod: 'getAlertDestinations' },
				default: [],
				description:
					'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
			},
			{
				displayName: 'Look Back (Minutes)',
				name: 'period',
				type: 'number',
				typeOptions: { minValue: 1 },
				default: 10,
				description: 'Scheduled alerts only',
			},
			{
				displayName: 'Operator',
				name: 'operator',
				type: 'options',
				default: '>=',
				options: ['=', '!=', '>', '>=', '<', '<='].map((value) => ({ name: value, value })),
			},
			{
				displayName: 'Query JSON',
				name: 'queryJson',
				type: 'json',
				default: '{}',
				description:
					'Fields to merge into the current query condition; include type when changing query mode',
			},
			{ displayName: 'Threshold', name: 'threshold', type: 'number', default: 1 },
		],
	},
	{ displayName: 'Clone Name', name: 'cloneName', type: 'string', default: '', ...show(['clone']) },
	{
		displayName: 'Clone Folder',
		name: 'cloneFolder',
		type: 'resourceLocator',
		default: { mode: 'list', value: '' },
		...show(['clone']),
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchAlertFolders', searchable: true },
			},
			{ displayName: 'By ID', name: 'id', type: 'string' },
		],
	},
	{
		displayName: 'Alert ID Filter',
		name: 'historyAlertId',
		type: 'string',
		default: '',
		...show(['getHistory']),
	},
	{
		displayName: 'Start Time',
		name: 'startTime',
		type: 'dateTime',
		default: '',
		...show(['getHistory']),
	},
	{
		displayName: 'End Time',
		name: 'endTime',
		type: 'dateTime',
		default: '',
		...show(['getHistory']),
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		...show(['getMany', 'getHistory']),
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		displayOptions: {
			show: { resource: ['alert'], operation: ['getMany', 'getHistory'], returnAll: [false] },
		},
	},
	{
		displayName: 'I Understand This Permanently Deletes the Alert',
		name: 'confirmDestructive',
		type: 'boolean',
		default: false,
		...show(['delete']),
	},
	{
		displayName: 'I Understand This Sends Notifications',
		name: 'confirmTrigger',
		type: 'boolean',
		default: false,
		...show(['trigger']),
	},
];
