import type { INodeProperties } from 'n8n-workflow';
const show = (operations: string[]) => ({
	displayOptions: { show: { resource: ['alertDestination'], operation: operations } },
});
export const alertDestinationProperties: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource: ['alertDestination'] } },
		default: 'create',
		options: [
			{ name: 'Create', value: 'create', action: 'Create an alert destination' },
			{ name: 'Delete', value: 'delete', action: 'Delete an alert destination' },
			{ name: 'Get', value: 'get', action: 'Get an alert destination' },
			{ name: 'Get Many', value: 'getMany', action: 'Get many alert destinations' },
			{ name: 'Update', value: 'update', action: 'Update an alert destination' },
		],
	},
	{
		displayName: 'Destination',
		name: 'destinationName',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		...show(['get', 'update', 'delete']),
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchAlertDestinations', searchable: true },
			},
			{ displayName: 'By Name', name: 'id', type: 'string' },
		],
	},
	{
		displayName: 'Name',
		name: 'name',
		type: 'string',
		required: true,
		default: '',
		...show(['create']),
	},
	{
		displayName: 'Template',
		name: 'templateName',
		type: 'resourceLocator',
		required: true,
		default: { mode: 'list', value: '' },
		...show(['create']),
		modes: [
			{
				displayName: 'From List',
				name: 'list',
				type: 'list',
				typeOptions: { searchListMethod: 'searchAlertTemplates', searchable: true },
			},
			{ displayName: 'By Name', name: 'id', type: 'string' },
		],
	},
	{
		displayName: 'URL',
		name: 'url',
		type: 'string',
		required: true,
		default: '',
		placeholder: 'https://example.com/webhook',
		...show(['create']),
	},
	{
		displayName: 'HTTP Method',
		name: 'httpMethod',
		type: 'options',
		default: 'post',
		options: [
			{ name: 'GET', value: 'get' },
			{ name: 'POST', value: 'post' },
			{ name: 'PUT', value: 'put' },
		],
		...show(['create']),
	},
	{
		displayName: 'Headers JSON',
		name: 'headersJson',
		type: 'json',
		default: '{}',
		description: 'Header values are treated as secrets and are redacted from node output',
		...show(['create']),
	},
	{
		displayName: 'Skip TLS Verification',
		name: 'skipTlsVerify',
		type: 'boolean',
		default: false,
		description:
			'Whether to skip certificate verification; use only for trusted self-hosted endpoints',
		...show(['create']),
	},
	{
		displayName: 'Destination JSON',
		name: 'destinationJson',
		type: 'json',
		default: '{}',
		description: 'Additional supported destination fields; webhook fields take precedence',
		...show(['create']),
	},
	{
		displayName: 'Update JSON',
		name: 'destinationJson',
		type: 'json',
		default: '{}',
		description:
			'Fields to merge into the current destination; the selected name cannot be changed. Header values are never returned.',
		...show(['update']),
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		description: 'Whether to return all results or only up to a given limit',
		...show(['getMany']),
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		typeOptions: { minValue: 1 },
		default: 50,
		description: 'Max number of results to return',
		displayOptions: {
			show: { resource: ['alertDestination'], operation: ['getMany'], returnAll: [false] },
		},
	},
	{
		displayName: 'I Understand This Permanently Deletes the Destination',
		name: 'confirmDestructive',
		type: 'boolean',
		default: false,
		...show(['delete']),
	},
];
